name: "Pupilfirst Reporting"
description: "Report test status for a submission in Pupilfirst LMS"
inputs:
  report_file_path:
    description: Relative path of the report JSON file that holds the test data
  status:
    description: Status to report to the LMS - queued/in_progress/completed.
  conclusion:
    description: Conclusion of the automated tests - success/failure/error. Only one of report_file_path or conclusion to be used. Will be ignored for queued/in_progress statuses.
  description:
    description: Description for the reported status
  test_mode:
    description: Set to true for debugging
    default: false
outputs:
  response: # output will be available to future steps
    description: "Response from the LMS"
runs:
  using: "node12"
  main: "../dist/reporting/index.js"
